parameters:
#    expresso_foo.example.class: Expresso\ExpressoFooBundle\Example

services:
#    expresso_foo.example:
#        class: %expresso_foo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
